name: juejin-auto-sign
permissions:
  contents: write
on:
  watch:
    types: [starred]
  schedule:
    # æ‰§è¡Œä¸¤æ¬¡ é¿å…å¶å°”æ‰§è¡Œå¤±è´¥çš„æƒ…å†µå‡ºçŽ°
    - cron: '15 22 * * *'
    - cron: '30 23 * * *'
  push:
    branches:
      - main
      - master

  # pull_request:
  # branches: [ master,main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Write environment variables to .env file
        run: |
          echo "USER_COOKIE=${{ secrets.USER_COOKIE }}" > .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> .env
          echo "EMAIL_PASS=${{ secrets.EMAIL_PASS }}" >> .env
          echo "USER_EMAIL=${{ secrets.USER_EMAIL }}" >> .env
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
      - name: Add .env file to version control
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: env
          FOLDER: ./
          GITHUB_TOKEN: ${{ secrets.ACTION_SECRET }}
          GIT_CONFIG_NAME: 'dextr7'
          GIT_CONFIG_EMAIL: 'action@h7ml.cn'
          COMMIT_MESSAGE: '[Bot] Deploy to GitHub Pages ðŸš€'
          CLEAN: true
          TARGET_FOLDER: ./
